<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
$post = $gloskin_context['post'];
$has_contact = $gloskin_context['address'] || $gloskin_context['phone_display'] || $gloskin_context['operating_hours'] || $gloskin_context['whatsapp_url'];
$has_location = $gloskin_context['map_embed'] || $gloskin_context['map_url'];
$has_details = gloskin_ui1_has_content( $post ) || $has_contact || $has_location;
$has_related = ! empty( $gloskin_context['doctors'] ) || ! empty( $gloskin_context['treatments'] );
?>
<section class="gloskin-ui1-detail-hero"><div class="gloskin-ui1-container gloskin-ui1-detail-hero__grid"><div><p class="gloskin-ui1-eyebrow"><?php echo esc_html__( 'Klinik Gloskin', 'gloskin-site-core' ); ?></p><h1><?php echo esc_html( get_the_title( $post ) ); ?></h1><?php if ( $gloskin_context['short_location'] ) : ?><p class="gloskin-ui1-lead"><?php echo esc_html( $gloskin_context['short_location'] ); ?></p><?php else : ?><p class="gloskin-ui1-lead"><?php echo esc_html__( 'Jelajahi informasi lokasi dan kanal kontak yang tersedia untuk klinik ini.', 'gloskin-site-core' ); ?></p><?php endif; ?></div><div class="gloskin-ui1-detail-hero__media"><?php if ( $gloskin_context['gallery_ids'] ) : ?><?php echo wp_get_attachment_image( $gloskin_context['gallery_ids'][0], 'large', false, array( 'class' => 'gloskin-ui1-detail-image' ) ); ?><?php else : ?><?php gloskin_ui1_render_presentation_media( 'clinic', get_the_title( $post ), 'gloskin-ui1-detail-abstract' ); ?><?php endif; ?></div></div></section>
<?php if ( count( $gloskin_context['gallery_ids'] ) > 1 ) : ?><section class="gloskin-ui1-section gloskin-ui1-section--tight"><div class="gloskin-ui1-container"><div class="gloskin-ui1-gallery"><?php foreach ( array_slice( $gloskin_context['gallery_ids'], 1 ) as $image_id ) { echo wp_get_attachment_image( $image_id, 'large', false, array( 'loading' => 'lazy', 'class' => 'gloskin-ui1-gallery__image' ) ); } ?></div></div></section><?php endif; ?>
<?php if ( $has_details ) : ?><section class="gloskin-ui1-section"><div class="gloskin-ui1-container<?php echo $has_location ? ' gloskin-ui1-detail-columns' : ' gloskin-ui1-container--narrow'; ?>"><div><?php gloskin_ui1_render_page_content( $post ); ?><?php if ( $has_contact ) : ?><div class="gloskin-ui1-contact-panel"><h2><?php echo esc_html__( 'Informasi Klinik', 'gloskin-site-core' ); ?></h2><?php if ( $gloskin_context['address'] ) : ?><p><strong><?php echo esc_html__( 'Alamat', 'gloskin-site-core' ); ?></strong><br><?php echo nl2br( esc_html( $gloskin_context['address'] ) ); ?></p><?php endif; ?><?php if ( $gloskin_context['phone_display'] ) : ?><p><strong><?php echo esc_html__( 'Telepon', 'gloskin-site-core' ); ?></strong><br><?php if ( $gloskin_context['phone_url'] ) : ?><a href="<?php echo esc_url( $gloskin_context['phone_url'] ); ?>"><?php echo esc_html( $gloskin_context['phone_display'] ); ?></a><?php else : ?><?php echo esc_html( $gloskin_context['phone_display'] ); ?><?php endif; ?></p><?php endif; ?><?php if ( $gloskin_context['operating_hours'] ) : ?><p><strong><?php echo esc_html__( 'Jam Operasional', 'gloskin-site-core' ); ?></strong><br><?php echo nl2br( esc_html( $gloskin_context['operating_hours'] ) ); ?></p><?php endif; ?><?php if ( $gloskin_context['whatsapp_url'] ) : ?><p><a class="gloskin-ui1-button gloskin-ui1-button--primary" href="<?php echo esc_url( $gloskin_context['whatsapp_url'] ); ?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html__( 'Hubungi via WhatsApp', 'gloskin-site-core' ); ?></a></p><?php endif; ?></div><?php endif; ?></div><?php if ( $has_location ) : ?><div><?php if ( $gloskin_context['map_embed'] ) : ?><div class="gloskin-ui1-map"><iframe title="<?php echo esc_attr( sprintf( __( 'Peta %s', 'gloskin-site-core' ), get_the_title( $post ) ) ); ?>" src="<?php echo esc_url( $gloskin_context['map_embed'] ); ?>" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe></div><?php else : ?><a class="gloskin-ui1-button gloskin-ui1-button--ghost" href="<?php echo esc_url( $gloskin_context['map_url'] ); ?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html__( 'Buka Peta', 'gloskin-site-core' ); ?></a><?php endif; ?></div><?php endif; ?></div></section><?php endif; ?>
<?php if ( $gloskin_context['doctors'] ) : ?><section class="gloskin-ui1-section gloskin-ui1-section--soft"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Dokter di Klinik Ini', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['doctors'], 'doctor' ); ?></div></section><?php endif; ?>
<?php if ( $gloskin_context['treatments'] ) : ?><section class="gloskin-ui1-section"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Perawatan Terkait', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['treatments'], 'treatment' ); ?></div></section><?php endif; ?>
<?php if ( ! $has_details && ! $has_related ) : ?><section class="gloskin-ui1-section gloskin-ui1-section--tight"><div class="gloskin-ui1-container gloskin-ui1-container--narrow"><?php gloskin_ui1_render_discovery_panel( __( 'Jelajahi jaringan klinik Gloskin', 'gloskin-site-core' ), __( 'Lihat seluruh lokasi atau gunakan halaman kontak untuk memilih klinik yang ingin Anda hubungi.', 'gloskin-site-core' ), __( 'Lihat Semua Klinik', 'gloskin-site-core' ), home_url( '/clinics/' ) ); ?></div></section><?php endif; ?>
