<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
gloskin_ui1_render_hero( $gloskin_context['hero'] );
?>
<section class="gloskin-ui1-section" data-gloskin-section="clinics-orientation"><div class="gloskin-ui1-container"><?php if ( gloskin_ui1_has_content( $gloskin_context['page'] ) ) : ?><div class="gloskin-ui1-container--narrow gloskin-ui1-section__intro"><?php gloskin_ui1_render_page_content( $gloskin_context['page'] ); ?></div><?php endif; ?><?php gloskin_ui1_render_editorial_split( __( 'Jaringan Klinik', 'gloskin-site-core' ), __( 'Pilih cabang dari daftar resmi yang tersedia di situs.', 'gloskin-site-core' ), __( 'Setiap halaman cabang menampilkan hanya alamat, jam, peta, galeri, dan kanal kontak yang memang sudah tersimpan. Detail yang belum tersedia tidak digantikan dengan data rekaan.', 'gloskin-site-core' ), __( 'Buka Kontak', 'gloskin-site-core' ), home_url( '/contact/' ), 'editorial' ); ?></div></section>
<section class="gloskin-ui1-section gloskin-ui1-section--soft" data-gloskin-section="clinics-grid"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Pilih Lokasi Gloskin', 'gloskin-site-core' ), __( 'Buka halaman cabang untuk melihat informasi faktual yang telah dipublikasikan.', 'gloskin-site-core' ) ); ?><?php gloskin_ui1_render_card_grid( $gloskin_context['clinics'], 'clinic' ); ?></div></section>
<?php if ( ! empty( $gloskin_context['doctors'] ) ) : ?><section class="gloskin-ui1-section" data-gloskin-section="clinics-doctors"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Profil Dokter yang Tersedia', 'gloskin-site-core' ), __( 'Buka profil untuk melihat informasi profesional dan lokasi praktik yang telah dihubungkan.', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['doctors'], 'doctor' ); ?></div></section><?php endif; ?>
<?php if ( ! empty( $gloskin_context['treatments'] ) ) : ?><section class="gloskin-ui1-section gloskin-ui1-section--soft" data-gloskin-section="clinics-treatments"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Perawatan yang Sudah Dipublikasikan', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['treatments'], 'treatment' ); ?></div></section><?php endif; ?>
<section class="gloskin-ui1-section gloskin-ui1-section--cta" data-gloskin-section="clinics-closing"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_closing_cta( __( 'Kontak', 'gloskin-site-core' ), __( 'Sudah menentukan cabang yang ingin dihubungi?', 'gloskin-site-core' ), __( 'Gunakan detail cabang atau halaman kontak untuk melanjutkan melalui kanal yang tersedia.', 'gloskin-site-core' ), __( 'Hubungi Gloskin', 'gloskin-site-core' ), home_url( '/contact/' ), __( 'Lihat Perawatan', 'gloskin-site-core' ), home_url( '/treatments/' ) ); ?></div></section>
