<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
$real_clinics = gloskin_ui1_real_cards( $gloskin_context['clinics'] );
gloskin_ui1_render_hero( $gloskin_context['hero'] );
?>
<section class="gloskin-ui1-section" data-gloskin-section="clinics-orientation"><div class="gloskin-ui1-container"><?php if ( gloskin_ui1_has_content( $gloskin_context['page'] ) ) : ?><div class="gloskin-ui1-container--narrow gloskin-ui1-section__intro"><?php gloskin_ui1_render_page_content( $gloskin_context['page'] ); ?></div><?php endif; ?><?php gloskin_ui1_render_editorial_split( __( 'Jaringan Klinik', 'gloskin-site-core' ), __( 'Pilih cabang Gloskin yang ingin Anda lihat lebih dekat.', 'gloskin-site-core' ), __( 'Buka halaman cabang untuk melihat alamat, jam operasional, peta, galeri, dan kanal kontak yang tersedia.', 'gloskin-site-core' ), __( 'Buka Kontak', 'gloskin-site-core' ), home_url( '/contact/' ), 'editorial' ); ?></div></section>
<section class="gloskin-ui1-section gloskin-ui1-section--soft" data-gloskin-section="clinics-grid"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Pilih Lokasi Gloskin', 'gloskin-site-core' ), __( 'Buka halaman cabang untuk melihat informasi lokasi dan kontak yang tersedia.', 'gloskin-site-core' ) ); ?><?php if ( $real_clinics ) : ?><?php gloskin_ui1_render_card_grid( $real_clinics, 'clinic' ); ?><?php else : ?><?php gloskin_ui1_render_empty_state( 'clinic', __( 'Belum ada klinik yang dapat ditampilkan', 'gloskin-site-core' ), __( 'Informasi lokasi akan tampil di sini setelah data klinik dipublikasikan.', 'gloskin-site-core' ), __( 'Hubungi Gloskin', 'gloskin-site-core' ), home_url( '/contact/' ) ); ?><?php endif; ?></div></section>
<?php if ( ! empty( $gloskin_context['doctors'] ) ) : ?><section class="gloskin-ui1-section" data-gloskin-section="clinics-doctors"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Profil Dokter yang Tersedia', 'gloskin-site-core' ), __( 'Buka profil untuk melihat informasi profesional dan lokasi praktik.', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['doctors'], 'doctor' ); ?></div></section><?php endif; ?>
<?php if ( ! empty( $gloskin_context['treatments'] ) ) : ?><section class="gloskin-ui1-section gloskin-ui1-section--soft" data-gloskin-section="clinics-treatments"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Informasi Perawatan', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['treatments'], 'treatment' ); ?></div></section><?php endif; ?>
<section class="gloskin-ui1-section gloskin-ui1-section--cta" data-gloskin-section="clinics-closing"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_closing_cta( __( 'Kontak', 'gloskin-site-core' ), __( 'Sudah menentukan cabang yang ingin dihubungi?', 'gloskin-site-core' ), __( 'Gunakan detail cabang atau halaman kontak untuk melanjutkan melalui kanal yang tersedia.', 'gloskin-site-core' ), __( 'Hubungi Gloskin', 'gloskin-site-core' ), home_url( '/contact/' ), __( 'Lihat Perawatan', 'gloskin-site-core' ), home_url( '/treatments/' ) ); ?></div></section>
