<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
$gloskin_post = $gloskin_context['post'];
$gloskin_has_contact = $gloskin_context['address'] || $gloskin_context['phone_display'] || $gloskin_context['operating_hours'] || $gloskin_context['whatsapp_url'];
$gloskin_has_location = $gloskin_context['map_embed'] || $gloskin_context['map_url'];
$gloskin_has_details = gloskin_ui1_has_content( $gloskin_post ) || $gloskin_has_contact || $gloskin_has_location;
$gloskin_booking_url = $gloskin_context['whatsapp_url'] ? $gloskin_context['whatsapp_url'] : home_url( '/contact/' );
/* translators: %s: the clinic's title, used as the embedded map iframe's accessible title. */
$gloskin_map_title = sprintf( __( 'Peta %s', 'gloskin-site-core' ), get_the_title( $gloskin_post ) );
?>
<section class="gloskin-ui1-detail-hero"><div class="gloskin-ui1-container gloskin-ui1-detail-hero__grid<?php echo $gloskin_context['gallery_ids'] ? '' : ' gloskin-ui1-detail-hero__grid--text-first'; ?>"><div><p class="gloskin-ui1-eyebrow"><?php echo esc_html__( 'Klinik Gloskin', 'gloskin-site-core' ); ?></p><h1><?php echo esc_html( get_the_title( $gloskin_post ) ); ?></h1><?php if ( $gloskin_context['short_location'] ) : ?><p class="gloskin-ui1-lead"><?php echo esc_html( $gloskin_context['short_location'] ); ?></p><?php else : ?><p class="gloskin-ui1-lead"><?php echo esc_html__( 'Lihat informasi cabang dan kanal kontak yang tersedia.', 'gloskin-site-core' ); ?></p><?php endif; ?></div><?php if ( $gloskin_context['gallery_ids'] ) : ?><div class="gloskin-ui1-detail-hero__media"><?php echo wp_get_attachment_image( $gloskin_context['gallery_ids'][0], 'large', false, array( 'class' => 'gloskin-ui1-detail-image', 'alt' => get_the_title( $gloskin_post ) ) ); ?></div><?php endif; ?></div></section>
<?php if ( count( $gloskin_context['gallery_ids'] ) > 1 ) : ?><section class="gloskin-ui1-section gloskin-ui1-section--tight" data-gloskin-section="clinic-gallery"><div class="gloskin-ui1-container"><div class="gloskin-ui1-gallery"><?php foreach ( array_slice( $gloskin_context['gallery_ids'], 1 ) as $gloskin_image_id ) { echo wp_get_attachment_image( $gloskin_image_id, 'large', false, array( 'loading' => 'lazy', 'class' => 'gloskin-ui1-gallery__image' ) ); } ?></div></div></section><?php endif; ?>
<?php if ( $gloskin_has_details ) : ?><section class="gloskin-ui1-section" data-gloskin-section="clinic-facts"><div class="gloskin-ui1-container<?php echo $gloskin_has_location ? ' gloskin-ui1-detail-columns' : ' gloskin-ui1-container--narrow'; ?>"><div><?php gloskin_ui1_render_page_content( $gloskin_post ); ?><?php if ( $gloskin_has_contact ) : ?><div class="gloskin-ui1-contact-panel"><h2><?php echo esc_html__( 'Informasi Klinik', 'gloskin-site-core' ); ?></h2><?php if ( $gloskin_context['address'] ) : ?><p><strong><?php echo esc_html__( 'Alamat', 'gloskin-site-core' ); ?></strong><br><?php echo nl2br( esc_html( $gloskin_context['address'] ) ); ?></p><?php endif; ?><?php if ( $gloskin_context['phone_display'] ) : ?><p><strong><?php echo esc_html__( 'Telepon', 'gloskin-site-core' ); ?></strong><br><?php if ( $gloskin_context['phone_url'] ) : ?><a href="<?php echo esc_url( $gloskin_context['phone_url'] ); ?>"><?php echo esc_html( $gloskin_context['phone_display'] ); ?></a><?php else : ?><?php echo esc_html( $gloskin_context['phone_display'] ); ?><?php endif; ?></p><?php endif; ?><?php if ( $gloskin_context['operating_hours'] ) : ?><p><strong><?php echo esc_html__( 'Jam Operasional', 'gloskin-site-core' ); ?></strong><br><?php echo nl2br( esc_html( $gloskin_context['operating_hours'] ) ); ?></p><?php endif; ?><?php if ( $gloskin_context['whatsapp_url'] ) : ?><p><a class="gloskin-ui1-button gloskin-ui1-button--primary" href="<?php echo esc_url( $gloskin_context['whatsapp_url'] ); ?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html__( 'Hubungi via WhatsApp', 'gloskin-site-core' ); ?></a></p><?php endif; ?></div><?php endif; ?></div><?php if ( $gloskin_has_location ) : ?><div><?php if ( $gloskin_context['map_embed'] ) : ?><div class="gloskin-ui1-map"><iframe title="<?php echo esc_attr( $gloskin_map_title ); ?>" src="<?php echo esc_url( $gloskin_context['map_embed'] ); ?>" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe></div><?php else : ?><a class="gloskin-ui1-button gloskin-ui1-button--ghost" href="<?php echo esc_url( $gloskin_context['map_url'] ); ?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html__( 'Buka Peta', 'gloskin-site-core' ); ?></a><?php endif; ?></div><?php endif; ?></div></section><?php else : ?><section class="gloskin-ui1-section" data-gloskin-section="clinic-sparse"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_editorial_split( __( 'Informasi Cabang', 'gloskin-site-core' ), __( 'Detail cabang belum tersedia untuk ditampilkan.', 'gloskin-site-core' ), __( 'Anda dapat kembali ke jaringan klinik atau menggunakan halaman kontak untuk mendapatkan informasi lebih lanjut.', 'gloskin-site-core' ), __( 'Semua Klinik', 'gloskin-site-core' ), home_url( '/clinics/' ), 'editorial' ); ?></div></section><?php endif; ?>
<?php if ( $gloskin_context['doctors'] ) : ?><section class="gloskin-ui1-section gloskin-ui1-section--soft" data-gloskin-section="clinic-doctors"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Dokter di Klinik Ini', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['doctors'], 'doctor' ); ?></div></section><?php endif; ?>
<?php if ( $gloskin_context['treatments'] ) : ?><section class="gloskin-ui1-section" data-gloskin-section="clinic-treatments"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Perawatan Terkait', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['treatments'], 'treatment' ); ?></div></section><?php endif; ?>
<section class="gloskin-ui1-section gloskin-ui1-section--cta" data-gloskin-section="clinic-closing"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_closing_cta( __( 'Hubungi Cabang', 'gloskin-site-core' ), __( 'Gunakan kanal yang tersedia untuk melanjutkan.', 'gloskin-site-core' ), __( 'Hubungi cabang melalui WhatsApp bila tersedia, atau gunakan halaman kontak Gloskin untuk pertanyaan lebih lanjut.', 'gloskin-site-core' ), $gloskin_context['whatsapp_url'] ? __( 'WhatsApp Klinik', 'gloskin-site-core' ) : __( 'Hubungi Gloskin', 'gloskin-site-core' ), $gloskin_booking_url, __( 'Semua Klinik', 'gloskin-site-core' ), home_url( '/clinics/' ) ); ?></div></section>
