<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
gloskin_ui1_render_hero( $gloskin_context['hero'] );
$gloskin_form_html = trim( (string) $gloskin_context['form_html'] );
$gloskin_form_available = '' !== $gloskin_form_html && false === strpos( $gloskin_form_html, 'gloskin-ui1-empty--form' );
$gloskin_real_clinics = gloskin_ui1_real_cards( $gloskin_context['clinics'] );
?>
<section class="gloskin-ui1-section" data-gloskin-section="contact-clinics"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_page_content( $gloskin_context['page'] ); ?><?php gloskin_ui1_render_section_heading( __( 'Pilih Lokasi yang Ingin Dihubungi', 'gloskin-site-core' ), __( 'Buka detail cabang untuk melihat kanal kontak yang sudah tersedia.', 'gloskin-site-core' ) ); ?><?php if ( $gloskin_real_clinics ) : ?><div class="gloskin-ui1-grid gloskin-ui1-grid--cards"><?php foreach ( $gloskin_real_clinics as $gloskin_clinic ) : ?><article class="gloskin-ui1-card gloskin-ui1-card--contact"><a class="gloskin-ui1-card__media" href="<?php echo esc_url( (string) $gloskin_clinic['url'] ); ?>" tabindex="-1" aria-hidden="true"><?php if ( ! empty( $gloskin_clinic['image_id'] ) ) : ?><?php echo wp_get_attachment_image( absint( $gloskin_clinic['image_id'] ), 'medium_large', false, array( 'loading' => 'lazy', 'class' => 'gloskin-ui1-card__image' ) ); ?><?php else : ?><?php gloskin_ui1_render_presentation_media( 'clinic', (string) $gloskin_clinic['title'], 'gloskin-ui1-card__abstract' ); ?><?php endif; ?></a><div class="gloskin-ui1-card__body"><h3 class="gloskin-ui1-card__title"><a href="<?php echo esc_url( (string) $gloskin_clinic['url'] ); ?>"><?php echo esc_html( (string) $gloskin_clinic['title'] ); ?></a></h3><?php if ( ! empty( $gloskin_clinic['phone_display'] ) ) : ?><p><?php echo esc_html( (string) $gloskin_clinic['phone_display'] ); ?></p><?php endif; ?><div class="gloskin-ui1-card__actions"><a class="gloskin-ui1-text-link" href="<?php echo esc_url( (string) $gloskin_clinic['url'] ); ?>"><?php echo esc_html__( 'Lihat Klinik', 'gloskin-site-core' ); ?></a><?php if ( ! empty( $gloskin_clinic['whatsapp_url'] ) ) : ?><a class="gloskin-ui1-button gloskin-ui1-button--small" href="<?php echo esc_url( (string) $gloskin_clinic['whatsapp_url'] ); ?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html__( 'Hubungi via WhatsApp', 'gloskin-site-core' ); ?></a><?php endif; ?></div></div></article><?php endforeach; ?></div><?php else : ?><?php gloskin_ui1_render_empty_state( 'clinic', __( 'Belum ada detail klinik yang dapat ditampilkan', 'gloskin-site-core' ), __( 'Anda tetap dapat menggunakan formulir kontak di bawah bila tersedia.', 'gloskin-site-core' ) ); ?><?php endif; ?></div></section>
<?php if ( $gloskin_form_available ) : ?><section class="gloskin-ui1-section gloskin-ui1-section--soft" data-gloskin-section="contact-form"><div class="gloskin-ui1-container gloskin-ui1-container--narrow"><?php gloskin_ui1_render_section_heading( __( 'Kirim Pesan', 'gloskin-site-core' ), __( 'Gunakan formulir ini untuk mengirim pertanyaan kepada Gloskin.', 'gloskin-site-core' ) ); ?><div class="gloskin-ui1-form"><?php echo $gloskin_form_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- configured provider output. ?></div></div></section><?php endif; ?>
