<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
gloskin_ui1_render_hero( $gloskin_context['hero'] );
?>
<section class="gloskin-ui1-section gloskin-ui1-section--discovery">
	<div class="gloskin-ui1-container">
		<?php gloskin_ui1_render_section_heading( __( 'Mulai dari yang ingin Anda ketahui', 'gloskin-site-core' ), __( 'Pilih jalur yang paling relevan untuk menjelajahi Gloskin.', 'gloskin-site-core' ) ); ?>
		<div class="gloskin-ui1-discovery-grid">
			<a class="gloskin-ui1-discovery-tile" href="<?php echo esc_url( home_url( '/treatments/' ) ); ?>"><span class="gloskin-ui1-eyebrow"><?php echo esc_html__( 'Informasi', 'gloskin-site-core' ); ?></span><strong><?php echo esc_html__( 'Kenali Perawatan', 'gloskin-site-core' ); ?></strong><span><?php echo esc_html__( 'Pelajari informasi perawatan yang telah dipublikasikan.', 'gloskin-site-core' ); ?></span></a>
			<a class="gloskin-ui1-discovery-tile" href="<?php echo esc_url( home_url( '/clinics/' ) ); ?>"><span class="gloskin-ui1-eyebrow"><?php echo esc_html__( 'Lokasi', 'gloskin-site-core' ); ?></span><strong><?php echo esc_html__( 'Temukan Klinik', 'gloskin-site-core' ); ?></strong><span><?php echo esc_html__( 'Jelajahi sembilan lokasi Gloskin.', 'gloskin-site-core' ); ?></span></a>
			<a class="gloskin-ui1-discovery-tile" href="<?php echo esc_url( home_url( '/skincare/' ) ); ?>"><span class="gloskin-ui1-eyebrow">Skincare</span><strong><?php echo esc_html__( 'Jelajahi Kategori', 'gloskin-site-core' ); ?></strong><span><?php echo esc_html__( 'Lihat kategori skincare Gloskin untuk perawatan harian.', 'gloskin-site-core' ); ?></span></a>
		</div>
	</div>
</section>
<?php if ( gloskin_ui1_has_content( $gloskin_context['page'] ) ) : ?><section class="gloskin-ui1-section"><div class="gloskin-ui1-container gloskin-ui1-container--narrow"><?php gloskin_ui1_render_page_content( $gloskin_context['page'] ); ?></div></section><?php endif; ?>
<?php if ( $gloskin_context['treatments'] ) : ?><section class="gloskin-ui1-section gloskin-ui1-section--soft"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Perawatan', 'gloskin-site-core' ), __( 'Kenali pilihan perawatan yang telah dipublikasikan Gloskin.', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['treatments'], 'treatment' ); ?><p class="gloskin-ui1-section__action"><a class="gloskin-ui1-text-link" href="<?php echo esc_url( home_url( '/treatments/' ) ); ?>"><?php echo esc_html__( 'Lihat Perawatan', 'gloskin-site-core' ); ?> →</a></p></div></section><?php endif; ?>
<section class="gloskin-ui1-section"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Jaringan Klinik', 'gloskin-site-core' ), __( 'Sembilan lokasi Gloskin untuk dijelajahi.', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['clinics'], 'clinic' ); ?><p class="gloskin-ui1-section__action"><a class="gloskin-ui1-text-link" href="<?php echo esc_url( home_url( '/clinics/' ) ); ?>"><?php echo esc_html__( 'Lihat Semua Klinik', 'gloskin-site-core' ); ?> →</a></p></div></section>
<section class="gloskin-ui1-section gloskin-ui1-section--soft"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Jelajahi Skincare', 'gloskin-site-core' ), __( 'Temukan kategori sesuai kebutuhan perawatan harian.', 'gloskin-site-core' ) ); ?><div class="gloskin-ui1-grid gloskin-ui1-grid--categories"><?php foreach ( $gloskin_context['skincare'] as $mapping ) { gloskin_ui1_render_category_link( $mapping ); } ?></div></div></section>
<?php if ( $gloskin_context['doctors'] ) : ?><section class="gloskin-ui1-section gloskin-ui1-section--contrast"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Dokter Gloskin', 'gloskin-site-core' ), __( 'Kenali profil profesional yang telah dipublikasikan.', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['doctors'], 'doctor' ); ?><p class="gloskin-ui1-section__action"><a class="gloskin-ui1-text-link" href="<?php echo esc_url( home_url( '/doctors/' ) ); ?>"><?php echo esc_html__( 'Lihat Profil Dokter', 'gloskin-site-core' ); ?> →</a></p></div></section><?php endif; ?>
<?php if ( $gloskin_context['products'] ) : ?><section class="gloskin-ui1-section"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Produk Gloskin', 'gloskin-site-core' ) ); ?><div class="gloskin-ui1-grid gloskin-ui1-grid--cards"><?php foreach ( $gloskin_context['products'] as $product ) { gloskin_ui1_render_product_card( $product ); } ?></div><p class="gloskin-ui1-section__action"><a class="gloskin-ui1-text-link" href="<?php echo esc_url( home_url( '/shop/' ) ); ?>"><?php echo esc_html__( 'Lihat Produk', 'gloskin-site-core' ); ?> →</a></p></div></section><?php endif; ?>
<?php if ( $gloskin_context['insights'] ) : ?><section class="gloskin-ui1-section<?php echo $gloskin_context['products'] ? ' gloskin-ui1-section--soft' : ''; ?>"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Insight', 'gloskin-site-core' ), __( 'Informasi dan pembaruan yang dipublikasikan Gloskin.', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['insights'], 'insight' ); ?></div></section><?php endif; ?>
<section class="gloskin-ui1-section gloskin-ui1-section--cta"><div class="gloskin-ui1-container gloskin-ui1-cta"><div><p class="gloskin-ui1-eyebrow"><?php echo esc_html__( 'Konsultasi', 'gloskin-site-core' ); ?></p><h2><?php echo esc_html__( 'Temukan klinik Gloskin untuk langkah berikutnya.', 'gloskin-site-core' ); ?></h2></div><a class="gloskin-ui1-button gloskin-ui1-button--primary" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>"><?php echo esc_html__( 'Hubungi Kami', 'gloskin-site-core' ); ?></a></div></section>
