<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
gloskin_ui1_render_hero( $gloskin_context['hero'] );
?>
<section class="gloskin-ui1-section" data-gloskin-section="skincare-intro"><div class="gloskin-ui1-container">
	<?php if ( gloskin_ui1_has_content( $gloskin_context['page'] ) ) : ?><div class="gloskin-ui1-container--narrow gloskin-ui1-section__intro"><?php gloskin_ui1_render_page_content( $gloskin_context['page'] ); ?></div><?php endif; ?>
	<?php gloskin_ui1_render_editorial_split( __( 'Skincare Gloskin', 'gloskin-site-core' ), __( 'Susun penjelajahan dari kategori, lalu lihat produk yang tersedia.', 'gloskin-site-core' ), __( 'Kategori membantu mempersempit halaman yang ingin dibuka. Detail produk, harga, dan ketersediaannya tetap bersumber dari WooCommerce.', 'gloskin-site-core' ), __( 'Buka Shop', 'gloskin-site-core' ), home_url( '/shop/' ), 'skincare', true ); ?>
</div></section>
<section class="gloskin-ui1-section gloskin-ui1-section--soft" data-gloskin-section="skincare-categories"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Kategori Skincare', 'gloskin-site-core' ), __( 'Pilih kategori untuk melihat landing page dan produk yang terhubung melalui WooCommerce.', 'gloskin-site-core' ) ); ?><div class="gloskin-ui1-grid gloskin-ui1-grid--categories"><?php foreach ( $gloskin_context['mappings'] as $mapping ) { gloskin_ui1_render_category_link( $mapping ); } ?></div></div></section>
<?php if ( $gloskin_context['products'] ) : ?><section class="gloskin-ui1-section" data-gloskin-section="skincare-products"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Produk yang Tersedia', 'gloskin-site-core' ), __( 'Informasi produk pada kartu berikut berasal dari katalog WooCommerce.', 'gloskin-site-core' ) ); ?><div class="gloskin-ui1-grid gloskin-ui1-grid--cards"><?php foreach ( $gloskin_context['products'] as $product ) { gloskin_ui1_render_product_card( $product ); } ?></div></div></section><?php endif; ?>
<section class="gloskin-ui1-section" data-gloskin-section="skincare-pathways"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_pathway_grid( array( array( 'eyebrow' => __( 'Katalog', 'gloskin-site-core' ), 'title' => __( 'Lihat seluruh pilihan di Shop', 'gloskin-site-core' ), 'copy' => __( 'Buka katalog WooCommerce tanpa memindahkan kepemilikan produk ke template Gloskin.', 'gloskin-site-core' ), 'label' => __( 'Buka Shop', 'gloskin-site-core' ), 'url' => home_url( '/shop/' ) ), array( 'eyebrow' => __( 'Klinik', 'gloskin-site-core' ), 'title' => __( 'Butuh jalur konsultasi?', 'gloskin-site-core' ), 'copy' => __( 'Gunakan halaman klinik untuk memilih lokasi dan kanal kontak yang tersedia.', 'gloskin-site-core' ), 'label' => __( 'Lihat Klinik', 'gloskin-site-core' ), 'url' => home_url( '/clinics/' ) ) ) ); ?></div></section>
