<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
gloskin_ui1_render_hero( $gloskin_context['hero'] );
?>
<section class="gloskin-ui1-section" data-gloskin-section="treatments-orientation"><div class="gloskin-ui1-container">
	<?php if ( gloskin_ui1_has_content( $gloskin_context['page'] ) ) : ?><div class="gloskin-ui1-container--narrow gloskin-ui1-section__intro"><?php gloskin_ui1_render_page_content( $gloskin_context['page'] ); ?></div><?php endif; ?>
	<?php gloskin_ui1_render_editorial_split( __( 'Sebelum memilih', 'gloskin-site-core' ), __( 'Baca konteksnya, lalu tentukan apa yang ingin dikonsultasikan.', 'gloskin-site-core' ), __( 'Gunakan informasi perawatan sebagai awal untuk menyiapkan pertanyaan. Kebutuhan personal dapat dibicarakan lebih lanjut melalui kanal konsultasi Gloskin.', 'gloskin-site-core' ), __( 'Buka Kontak', 'gloskin-site-core' ), home_url( '/contact/' ), 'treatment', true ); ?>
</div></section>
<?php if ( ! empty( $gloskin_context['featured_treatment'] ) ) : ?><section class="gloskin-ui1-section gloskin-ui1-section--soft" data-gloskin-section="treatments-featured"><div class="gloskin-ui1-container"><div class="gloskin-ui1-featured-entry"><div><p class="gloskin-ui1-eyebrow"><?php echo esc_html__( 'Sorotan', 'gloskin-site-core' ); ?></p><h2><?php echo esc_html__( 'Perawatan untuk dilihat lebih dekat', 'gloskin-site-core' ); ?></h2><p><?php echo esc_html__( 'Buka halaman perawatan untuk membaca informasi yang tersedia.', 'gloskin-site-core' ); ?></p></div><div><?php gloskin_ui1_render_card( $gloskin_context['featured_treatment'], 'treatment' ); ?></div></div></div></section><?php endif; ?>
<section class="gloskin-ui1-section" data-gloskin-section="treatments-discovery"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Informasi Perawatan', 'gloskin-site-core' ), __( 'Buka setiap halaman untuk membaca informasi yang tersedia.', 'gloskin-site-core' ) ); ?><?php if ( $gloskin_context['treatments'] ) : ?><?php gloskin_ui1_render_card_grid( $gloskin_context['treatments'], 'treatment' ); ?><?php else : ?><?php gloskin_ui1_empty( __( 'Belum ada perawatan tambahan yang dapat ditampilkan.', 'gloskin-site-core' ) ); ?><?php endif; ?></div></section>
<section class="gloskin-ui1-section gloskin-ui1-section--soft" data-gloskin-section="treatments-pathways"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Lanjutkan dari konteks yang Anda perlukan', 'gloskin-site-core' ), __( 'Padukan informasi perawatan dengan lokasi klinik atau profil dokter yang tersedia.', 'gloskin-site-core' ) ); gloskin_ui1_render_pathway_grid( array_filter( array( array( 'eyebrow' => __( 'Lokasi', 'gloskin-site-core' ), 'title' => __( 'Lihat jaringan klinik', 'gloskin-site-core' ), 'copy' => __( 'Pilih cabang dan lihat kanal kontak yang tersedia.', 'gloskin-site-core' ), 'label' => __( 'Buka Klinik', 'gloskin-site-core' ), 'url' => home_url( '/clinics/' ) ), ! empty( $gloskin_context['doctors'] ) ? array( 'eyebrow' => __( 'Profil', 'gloskin-site-core' ), 'title' => __( 'Kenali dokter Gloskin', 'gloskin-site-core' ), 'copy' => __( 'Baca profil profesional dan lokasi praktik yang tersedia.', 'gloskin-site-core' ), 'label' => __( 'Buka Dokter', 'gloskin-site-core' ), 'url' => home_url( '/doctors/' ) ) : null, array( 'eyebrow' => __( 'Konsultasi', 'gloskin-site-core' ), 'title' => __( 'Sampaikan pertanyaan Anda', 'gloskin-site-core' ), 'copy' => __( 'Gunakan halaman kontak untuk menanyakan langkah berikutnya.', 'gloskin-site-core' ), 'label' => __( 'Buka Kontak', 'gloskin-site-core' ), 'url' => home_url( '/contact/' ) ) ) ) ); ?></div></section>
<section class="gloskin-ui1-section gloskin-ui1-section--cta" data-gloskin-section="treatments-closing"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_closing_cta( __( 'Konsultasi', 'gloskin-site-core' ), __( 'Informasi di situs membantu menyiapkan pertanyaan sebelum konsultasi.', 'gloskin-site-core' ), __( 'Pilih klinik atau gunakan halaman kontak untuk melanjutkan melalui kanal yang tersedia.', 'gloskin-site-core' ), __( 'Pilih Klinik', 'gloskin-site-core' ), home_url( '/clinics/' ), __( 'Hubungi Gloskin', 'gloskin-site-core' ), home_url( '/contact/' ) ); ?></div></section>
