<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
$gloskin_post = $gloskin_context['post'];
$gloskin_has_details = gloskin_ui1_has_content( $gloskin_post ) || $gloskin_context['benefits'] || $gloskin_context['contraindications'];
$gloskin_booking_url = $gloskin_context['booking_target'] ? $gloskin_context['booking_target'] : home_url( '/contact/' );
?>
<section class="gloskin-ui1-detail-hero"><div class="gloskin-ui1-container gloskin-ui1-detail-hero__grid"><div><p class="gloskin-ui1-eyebrow"><?php echo esc_html__( 'Perawatan', 'gloskin-site-core' ); ?></p><h1><?php echo esc_html( get_the_title( $gloskin_post ) ); ?></h1><?php if ( $gloskin_context['summary'] ) : ?><p class="gloskin-ui1-lead"><?php echo esc_html( $gloskin_context['summary'] ); ?></p><?php endif; ?></div><div class="gloskin-ui1-detail-hero__media"><?php if ( $gloskin_context['image_id'] ) : ?><?php echo wp_get_attachment_image( $gloskin_context['image_id'], 'large', false, array( 'class' => 'gloskin-ui1-detail-image' ) ); ?><?php else : ?><?php gloskin_ui1_render_presentation_media( 'treatment', get_the_title( $gloskin_post ), 'gloskin-ui1-detail-abstract' ); ?><?php endif; ?></div></div></section>
<?php if ( $gloskin_has_details ) : ?><section class="gloskin-ui1-section" data-gloskin-section="treatment-facts"><div class="gloskin-ui1-container gloskin-ui1-container--narrow"><?php gloskin_ui1_render_page_content( $gloskin_post ); ?><?php if ( $gloskin_context['benefits'] ) : ?><div class="gloskin-ui1-detail-block"><h2><?php echo esc_html__( 'Manfaat', 'gloskin-site-core' ); ?></h2><div class="gloskin-ui1-prose"><?php echo wp_kses_post( $gloskin_context['benefits'] ); ?></div></div><?php endif; ?><?php if ( $gloskin_context['contraindications'] ) : ?><div class="gloskin-ui1-detail-block"><h2><?php echo esc_html__( 'Kontraindikasi', 'gloskin-site-core' ); ?></h2><div class="gloskin-ui1-prose"><?php echo wp_kses_post( $gloskin_context['contraindications'] ); ?></div></div><?php endif; ?></div></section><?php endif; ?>
<section class="gloskin-ui1-section<?php echo $gloskin_has_details ? ' gloskin-ui1-section--soft' : ''; ?>" data-gloskin-section="treatment-orientation"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_editorial_split( __( 'Untuk dipertimbangkan', 'gloskin-site-core' ), __( 'Gunakan informasi yang tersedia sebagai bahan sebelum berbicara dengan klinik.', 'gloskin-site-core' ), __( 'Catat pertanyaan yang ingin Anda bahas dan gunakan kanal konsultasi Gloskin untuk mendapatkan informasi lebih lanjut sesuai kebutuhan Anda.', 'gloskin-site-core' ), __( 'Buka Kontak', 'gloskin-site-core' ), home_url( '/contact/' ), 'treatment' ); ?></div></section>
<?php if ( $gloskin_context['clinics'] ) : ?><section class="gloskin-ui1-section" data-gloskin-section="treatment-clinics"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Klinik Terkait', 'gloskin-site-core' ), __( 'Lihat lokasi Gloskin yang terkait dengan perawatan ini.', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['clinics'], 'clinic' ); ?></div></section><?php endif; ?>
<?php if ( $gloskin_context['doctors'] ) : ?><section class="gloskin-ui1-section gloskin-ui1-section--soft" data-gloskin-section="treatment-doctors"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Dokter Terkait', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['doctors'], 'doctor' ); ?></div></section><?php endif; ?>
<?php if ( ! empty( $gloskin_context['related_treatments'] ) ) : ?><section class="gloskin-ui1-section" data-gloskin-section="treatment-related"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Informasi Perawatan Lain', 'gloskin-site-core' ), __( 'Buka halaman lain bila Anda masih membandingkan informasi yang tersedia.', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['related_treatments'], 'treatment' ); ?></div></section><?php endif; ?>
<section class="gloskin-ui1-section gloskin-ui1-section--cta" data-gloskin-section="treatment-closing"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_closing_cta( __( 'Langkah Berikutnya', 'gloskin-site-core' ), __( 'Bicarakan pertanyaan yang belum terjawab melalui kanal Gloskin.', 'gloskin-site-core' ), __( 'Gunakan jalur konsultasi yang tersedia untuk perawatan ini, atau lanjutkan ke halaman kontak.', 'gloskin-site-core' ), __( 'Lanjutkan Konsultasi', 'gloskin-site-core' ), $gloskin_booking_url, __( 'Semua Perawatan', 'gloskin-site-core' ), home_url( '/treatments/' ) ); ?></div></section>
