---
deployment:
  tasks:
    - export MUPATH=/home/markascl/gloskin-id.markas.cloud/wp-content/mu-plugins/
    - /bin/rm -f $MUPATH/000-markas-auth-guard.php
    - export DEPLOYPATH=/home/markascl/gloskin-id.markas.cloud/wp-content/plugins/gloskin-site-core/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R plugin/gloskin-site-core/. $DEPLOYPATH
