"""Static contract: admin render and asset wiring for v0.7.163 AJAX flow."""
import os,sys
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def read(path):
    with open(os.path.join(ROOT,path),encoding='utf-8') as f:return f.read()
failures=[]
def require(cond,msg):
    if not cond:failures.append(msg)
admin_php=read('plugin/gloskin-site-core/includes/class-gloskin-site-core-revision-20260819-final-migration-admin.php'); asset_svc=read('plugin/gloskin-site-core/includes/class-gloskin-site-core-asset-service.php'); assets_cfg=read('plugin/gloskin-site-core/config/assets.php'); kernel=read('plugin/gloskin-site-core/includes/class-gloskin-site-core-kernel.php'); plugin_h=read('plugin/gloskin-site-core/gloskin-site-core.php'); js_path=os.path.join(ROOT,'plugin/gloskin-site-core/assets/js/gloskin-ui1-final-migration.js'); js_exists=os.path.isfile(js_path); js=read('plugin/gloskin-site-core/assets/js/gloskin-ui1-final-migration.js') if js_exists else ''
require('data-gloskin-final-migration' in admin_php,'Admin render must include data-gloskin-final-migration attribute on root div'); require('data-gloskin-migration-form' in admin_php,'Admin render must include data-gloskin-migration-form on the POST form'); require('data-gloskin-migration-run' in admin_php,'Admin render must include data-gloskin-migration-run on the submit button'); require('data-gloskin-migration-progressbar' in admin_php,'Admin render must include data-gloskin-migration-progressbar on progress element'); require('data-gloskin-migration-step' in admin_php,'Admin render must include data-gloskin-migration-step on step paragraph'); require('data-gloskin-migration-error' in admin_php,'Admin render must include data-gloskin-migration-error for inline error div'); require('enqueue_admin_final_migration' in admin_php,'enqueue_assets() must call enqueue_admin_final_migration()'); require('enqueue_admin_migration(' not in admin_php,'enqueue_assets() must NOT call old enqueue_admin_migration()'); require('function enqueue_admin_final_migration' in asset_svc,'Asset service must define enqueue_admin_final_migration() method'); require('gloskin-ui1-final-migration' in assets_cfg,'config/assets.php must register gloskin-ui1-final-migration admin script'); require('gloskin-ui1-final-migration.js' in assets_cfg,'config/assets.php must point gloskin-ui1-final-migration to the correct JS file'); require(js_exists,'assets/js/gloskin-ui1-final-migration.js must exist on disk'); require('[data-gloskin-final-migration]' in js,'New JS must select root element via [data-gloskin-final-migration]'); require("getAttribute( 'data-ajax' )" in js or "getAttribute('data-ajax')" in js,'New JS must read data-ajax from root element attribute'); require("getAttribute( 'data-action' )" in js or "getAttribute('data-action')" in js,'New JS must read data-action from root element attribute'); require("getAttribute( 'data-nonce' )" in js or "getAttribute('data-nonce')" in js,'New JS must read data-nonce from root element attribute'); require('data-gloskin-sample-import' not in js,'New JS must NOT contain old [data-gloskin-sample-import] selector'); require('data-gloskin-ia-migration' not in js,'New JS must NOT contain old [data-gloskin-ia-migration] selector'); require("Version: 0.7.163" in plugin_h,'Plugin header must be 0.7.163'); require("const VERSION = '0.7.163';" in kernel,'Kernel VERSION must be 0.7.163')
if failures:
    for f in failures:print('FAIL:',f)
    sys.exit(1)
print('final-migration-dom-contract.py: OK (0.7.163)')
