"""Static contract: design_variant and header_variant fully retired from active runtime."""
import sys,os
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def read(path):
    with open(os.path.join(ROOT,path),encoding='utf-8') as f:return f.read()
failures=[]
def require(cond,msg):
    if not cond:failures.append(msg)
svc=read('plugin/gloskin-site-core/includes/class-gloskin-site-core-template-service.php');woo=read('plugin/gloskin-site-core/includes/class-gloskin-site-core-woocommerce-adapter.php');admin=read('plugin/gloskin-site-core/includes/class-gloskin-site-core-admin-service.php');kernel=read('plugin/gloskin-site-core/includes/class-gloskin-site-core-kernel.php');shell=read('plugin/gloskin-site-core/templates/shell.php');header=read('plugin/gloskin-site-core/templates/parts/header.php');plugin_h=read('plugin/gloskin-site-core/gloskin-site-core.php')
require("$context['design_variant']" not in svc,"$context['design_variant'] must not be projected in template-service");require("$context['header_variant']" not in svc,"$context['header_variant'] must not be projected in template-service");require('private function design_variant()' not in svc and 'function design_variant(' not in svc,'private function design_variant() must be fully removed from template-service');require('private function header_variant()' not in svc and 'function header_variant(' not in svc,'private function header_variant() must be fully removed from template-service');require("settings['design_variant']" not in woo and 'design_variant' not in woo,'body_classes() in woocommerce-adapter must not read design_variant from settings');require("'design_variant' => 'medical'" not in admin,'design_variant must be removed from settings_defaults() in admin-service');require("'header_variant' => 'header-1'" not in admin,'header_variant must be removed from settings_defaults() in admin-service');require("sanitize_key( $value['design_variant'] )" not in admin and "value['design_variant']" not in admin,'design_variant must be removed from sanitize_settings() in admin-service');require("sanitize_key( $value['header_variant'] )" not in admin and "value['header_variant']" not in admin,'header_variant must be removed from sanitize_settings() in admin-service');require('design_variant]"' not in admin,'design_variant hidden input must not appear in admin settings UI');require('header_variant]"' not in admin,'header_variant hidden input must not appear in admin settings UI');require('function header_variant_previews()' not in admin,'header_variant_previews() must be removed from admin-service (zero consumers)');require('function render_header_variant_card(' not in admin,'render_header_variant_card() must be removed from admin-service (zero consumers)');require('class-gloskin-site-core-prototype-ia-migration-admin.php' not in kernel,'Prototype IA Migration admin must NOT be registered in kernel (single migration action)');require('Gloskin_Site_Core_Prototype_IA_Migration_Admin' not in kernel,'Gloskin_Site_Core_Prototype_IA_Migration_Admin must NOT be instantiated in kernel');require('class-gloskin-site-core-insight-migration-admin.php' in kernel,'Insight Migration admin MUST remain registered in kernel (genuinely independent)');require('design_variant' not in shell,'Public shell must not consume design_variant');require('header_variant' not in shell,'Public shell must not consume header_variant');require('header_variant' not in header,'Public header must not read header_variant state');require('Version: 0.7.156' in plugin_h,'plugin header must be 0.7.156');require("const VERSION = '0.7.156';" in kernel,'Kernel VERSION must be 0.7.156')
if failures:
    for f in failures:print('FAIL:',f)
    sys.exit(1)
print('no-active-variant-context-contract.py: OK (0.7.156)')
