#!/usr/bin/env python3
from pathlib import Path
import re
ROOT = Path(__file__).resolve().parents[1]
def read(rel): return (ROOT / rel).read_text(encoding="utf-8")
def require(cond, message):
    if not cond: raise AssertionError(message)
shell = read("plugin/gloskin-site-core/templates/shell.php")
css = read("plugin/gloskin-site-core/assets/css/gloskin-ui1-loader-system.css")
js = read("plugin/gloskin-site-core/assets/js/gloskin-ui1-core.js")
runtime = read("tests/check-runtime.sh")
canonical_path = 'M647 271H415V239H528V120C528 102 527 88 523 80C520 69 501 56 466 44C428 29 392 21 357 22C300 23 255 53 221 112C187 172 170 249 170 345C170 555 235 665 365 673C481 679 530 624 539 510H569V667C531 682 506 690 495 692C462 700 417 704 360 704C275 704 204 672 145 607C86 539 56 453 55 345C54 246 83 161 142 90C204 21 275 -14 360 -14C419 -14 468 -8 509 2C544 13 578 25 613 35V239H647Z'
require(shell.count('class="gloskin-ui1-page-transition" data-gloskin-page-transition') == 1, "exactly one transition root")
require(canonical_path in shell, "exact canonical G path")
require('fill="#fff"' in shell or 'fill="#FFFFFF"' in shell, "canonical G is white")
require('viewBox="82 74 185 232"' in shell and 'translate(65,300) scale(0.3117268,-0.32)' in shell, "canonical G geometry")
require("--gl-transition-bg:#FFF2EB" in css, "warm transition background")
require("--gl-transition-jelly:#CA050E" in css, "canonical jelly red")
require("--gl-transition-g-size:104px" in css, "desktop G/jelly footprint")
require("--gl-transition-g-size:84px" in css, "mobile G/jelly footprint")
require(".gloskin-ui1-page-transition.is-active .gloskin-ui1-page-transition__blob" in css, "will-change only while active")
base_blob = css[css.index('.gloskin-ui1-page-transition__blob{'):css.index('}', css.index('.gloskin-ui1-page-transition__blob{'))]
require('will-change' not in base_blob, "no permanent border-radius will-change")
require("@media (prefers-reduced-motion:reduce){" in css and ".gloskin-ui1-page-transition{transition:none}" in css, "reduced motion")
require(js.count("function initPageTransitions()") == 1, "one initPageTransitions owner")
pt = js[js.index("function initPageTransitions()"):js.index("\n\tfunction init()", js.index("function initPageTransitions()"))]
require("sessionStorage" not in pt, "no sessionStorage")
require("beforeunload" not in pt and "'unload'" not in pt and '"unload"' not in pt, "no unload handlers")
require("barba" not in pt.lower() and "swup" not in pt.lower() and "fetch(" not in pt, "no SPA library/fetch owner")
m = re.search(r"EXIT_NAV_DELAY_MS\s*=\s*(\d+)", pt); require(m is not None, "EXIT_NAV_DELAY_MS exists")
delay = int(m.group(1)); require(80 <= delay <= 120, "EXIT_NAV_DELAY_MS is 80-120ms")
require("--gl-transition-duration" not in pt and "getTransitionDurationMs" not in pt, "navigation timing independent from CSS fade")
require(pt.count("location.href = href") == 1, "one location navigation attempt")
require(pt.count("requestAnimationFrame") >= 2, "one-two RAF paint opportunity")
require("STALE_UI_TIMEOUT_MS = 3000" in pt and "clearTransitionState" in pt and "navigated = false" in pt, "stale timeout clears UI/state")
stale = pt[pt.index("staleTimer = window.setTimeout"):]; require("location.href" not in stale, "stale timeout never redirects")
require("e.persisted" in pt and "'pageshow'" in pt, "BFCache pageshow cleanup")
require("e.metaKey" in pt and "e.ctrlKey" in pt and "e.shiftKey" in pt and "e.altKey" in pt, "modifier bypass")
require("target === '_blank'" in pt, "_blank bypass")
require("url.host !== location.host" in pt, "external bypass")
require("url.hash && url.pathname === location.pathname" in pt, "same-page anchor bypass")
require("ajax_add_to_cart" in pt and "add-to-cart=" in pt and "wc-ajax=" in pt, "AJAX add-to-cart bypass")
require("wishlist" in pt.lower() and ".variations" in pt and ".quantity" in pt and "form.checkout" in pt, "Woo action controls bypass")
require("commerceHandoffOwns" in pt, "existing cart-checkout handoff remains state owner")
require("'/product/'" not in pt and '"/product/"' not in pt, "normal PDP link eligible")
require("page-transition-contract.py" in runtime, "contract registered in runtime suite")
require("gloskin-ui1-commerce-handoff__g" in shell and canonical_path in shell[shell.index("gloskin-ui1-commerce-handoff"):], "commerce handoff reuses canonical white G visually")
print("page-transition-contract: OK (0.7.148 final closure)")
