<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
$gloskin_post = $gloskin_context['post'];
$gloskin_has_details = gloskin_ui1_has_content( $gloskin_post ) || $gloskin_context['profile'] || $gloskin_context['credentials'] || $gloskin_context['sip_number'] || $gloskin_context['schedule'];
$gloskin_booking_url = $gloskin_context['booking_target'] ? $gloskin_context['booking_target'] : home_url( '/contact/' );
?>
<section class="gloskin-ui1-detail-hero"><div class="gloskin-ui1-container gloskin-ui1-detail-hero__grid<?php echo $gloskin_context['image_id'] ? '' : ' gloskin-ui1-detail-hero__grid--text-first'; ?>"><div><p class="gloskin-ui1-eyebrow"><?php echo esc_html__( 'Dokter Gloskin', 'gloskin-site-core' ); ?></p><h1><?php echo esc_html( get_the_title( $gloskin_post ) ); ?></h1><?php if ( $gloskin_context['degree_title'] ) : ?><p class="gloskin-ui1-lead"><?php echo esc_html( $gloskin_context['degree_title'] ); ?></p><?php endif; ?><?php if ( $gloskin_context['specialization'] ) : ?><p><?php echo esc_html( $gloskin_context['specialization'] ); ?></p><?php endif; ?></div><?php if ( $gloskin_context['image_id'] ) : ?><div class="gloskin-ui1-detail-hero__media"><?php echo wp_get_attachment_image( $gloskin_context['image_id'], 'large', false, array( 'class' => 'gloskin-ui1-detail-image', 'alt' => get_the_title( $gloskin_post ) ) ); ?></div><?php endif; ?></div></section>
<?php if ( $gloskin_has_details ) : ?><section class="gloskin-ui1-section" data-gloskin-section="doctor-facts"><div class="gloskin-ui1-container gloskin-ui1-container--narrow"><?php gloskin_ui1_render_page_content( $gloskin_post ); ?><?php if ( $gloskin_context['profile'] ) : ?><div class="gloskin-ui1-detail-block"><h2><?php echo esc_html__( 'Profil', 'gloskin-site-core' ); ?></h2><div class="gloskin-ui1-prose"><?php echo wp_kses_post( $gloskin_context['profile'] ); ?></div></div><?php endif; ?><?php if ( $gloskin_context['credentials'] ) : ?><div class="gloskin-ui1-detail-block"><h2><?php echo esc_html__( 'Kredensial', 'gloskin-site-core' ); ?></h2><div class="gloskin-ui1-prose"><?php echo wp_kses_post( $gloskin_context['credentials'] ); ?></div></div><?php endif; ?><?php if ( $gloskin_context['sip_number'] ) : ?><p><strong>SIP:</strong> <?php echo esc_html( $gloskin_context['sip_number'] ); ?></p><?php endif; ?><?php if ( $gloskin_context['schedule'] ) : ?><div class="gloskin-ui1-detail-block"><h2><?php echo esc_html__( 'Jadwal', 'gloskin-site-core' ); ?></h2><p><?php echo nl2br( esc_html( $gloskin_context['schedule'] ) ); ?></p></div><?php endif; ?></div></section><?php else : ?><section class="gloskin-ui1-section" data-gloskin-section="doctor-sparse"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_editorial_split( __( 'Profil Profesional', 'gloskin-site-core' ), __( 'Detail tambahan belum tersedia untuk ditampilkan.', 'gloskin-site-core' ), __( 'Anda tetap dapat melihat jaringan klinik atau menggunakan halaman kontak untuk menentukan langkah berikutnya.', 'gloskin-site-core' ), __( 'Lihat Klinik', 'gloskin-site-core' ), home_url( '/clinics/' ), 'editorial' ); ?></div></section><?php endif; ?>
<?php if ( $gloskin_context['branches'] ) : ?><section class="gloskin-ui1-section gloskin-ui1-section--soft" data-gloskin-section="doctor-branches"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Lokasi Praktik', 'gloskin-site-core' ), __( 'Lihat cabang tempat dokter ini berpraktik.', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['branches'], 'clinic' ); ?></div></section><?php endif; ?>
<?php if ( $gloskin_context['treatments'] ) : ?><section class="gloskin-ui1-section" data-gloskin-section="doctor-treatments"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_section_heading( __( 'Perawatan Terkait', 'gloskin-site-core' ), __( 'Lihat informasi perawatan yang terkait dengan profil ini.', 'gloskin-site-core' ) ); gloskin_ui1_render_card_grid( $gloskin_context['treatments'], 'treatment' ); ?></div></section><?php endif; ?>
<section class="gloskin-ui1-section gloskin-ui1-section--cta" data-gloskin-section="doctor-closing"><div class="gloskin-ui1-container"><?php gloskin_ui1_render_closing_cta( __( 'Konsultasi', 'gloskin-site-core' ), __( 'Lanjutkan melalui jalur konsultasi yang tersedia.', 'gloskin-site-core' ), __( 'Buka tujuan konsultasi pada profil ini atau gunakan halaman kontak Gloskin untuk informasi lebih lanjut.', 'gloskin-site-core' ), __( 'Lanjutkan Konsultasi', 'gloskin-site-core' ), $gloskin_booking_url, __( 'Lihat Klinik', 'gloskin-site-core' ), home_url( '/clinics/' ) ); ?></div></section>
